name: Daily Email Automation
on:
  schedule:
    - cron: '0 8 * * *'  # 8:00 AM UTC daily
  workflow_dispatch:     # Allow manual trigger

jobs:
  send-daily-email:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Up Replit App
        run: |
          echo "Waking up Replit app..."
          curl -k -s "https://workspace.th106.replit.app/" || echo "Wake attempt completed"
          sleep 10
          
      - name: Trigger Daily Email
        run: |
          echo "Triggering daily email..."
          
          # Try the force-email-now endpoint with proper headers
          response=$(curl -k -s -w "%{http_code}" -X GET \
            "https://workspace.th106.replit.app/force-email-now" \
            -H "User-Agent: GitHub-Actions-Daily-Email" \
            -H "Accept: application/json" \
            -o response.txt)
          
          echo "Response code: $response"
          echo "Response content:"
          cat response.txt
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Daily email triggered successfully"
          else
            echo "⚠️ Trying alternative webhook method..."
            
            # Try webhook endpoint as backup
            webhook_response=$(curl -k -s -w "%{http_code}" -X POST \
              "https://workspace.th106.replit.app/webhook/trigger-daily-email" \
              -H "Authorization: daily_email_trigger_2025" \
              -H "Content-Type: application/json" \
              -o webhook_response.txt)
            
            echo "Webhook response code: $webhook_response"
            cat webhook_response.txt
            
            if [ "$webhook_response" -eq 200 ]; then
              echo "✅ Email triggered via webhook successfully"
            else
              echo "❌ Both methods failed"
              exit 1
            fi
          fi
          
      - name: Verify Email Sent
        run: |
          echo "Verifying email was sent..."
          sleep 5
          
          # Check email status
          status=$(curl -k -s "https://workspace.th106.replit.app/webhook/email-status" || echo "Status check failed")
          echo "Email status response:"
          echo "$status"
          
          # Check if emails were sent today
          if echo "$status" | grep -q '"emails_sent_today":[1-9]'; then
            echo "✅ Email delivery confirmed"
          else
            echo "⚠️ Email status unclear but trigger completed"
          fi
