name: Daily M&A Email
on:
  schedule:
    - cron: '0 8 * * *'  # 8:00 AM UTC daily
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Email
        run: |
          echo "=== TRIGGERING DAILY EMAIL ==="
          
          # Use the correct dev domain URL
          REPLIT_URL="https://9c85f1d2-50d7-42b9-a9cd-77a701b9e6c3-00-3lszl56i9z1hn.worf.replit.dev"
          
          echo "Using URL: $REPLIT_URL/daily-email-trigger"
          
          # Wake up the app
          echo "Waking up Replit app..."
          curl -k -s -m 30 "$REPLIT_URL/" || echo "Wake completed"
          sleep 10
          
          # Trigger email
          echo "Sending email trigger request..."
          response=$(curl -k -s -w "%{http_code}" -m 60 \
            "$REPLIT_URL/daily-email-trigger" \
            -o response.txt 2>/dev/null || echo "000")
          
          echo "Response code: $response"
          if [[ -f response.txt ]]; then
            echo "Response content:"
            cat response.txt
          fi
          
          # Check for success
          if [[ "$response" == "200" ]]; then
            echo "✅ SUCCESS: Daily email triggered"
            
            # Double-check with status
            sleep 5
            curl -k -s "$REPLIT_URL/webhook/email-status" || echo "Status check completed"
            
          else
            echo "⚠️ Response code: $response (trigger attempted)"
          fi
          
          echo "=== EMAIL TRIGGER COMPLETED ==="
